name: main
attributes:
  ORGANIZATIONNAME: st.crexi

projectReferences:
  View:
    path: ../View/View.xcodeproj
  UseCase:
    path: ../UseCase/UseCase.xcodeproj
  DataSource:
    path: ../DataSource/DataSource.xcodeproj
targets:
  main:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: AppIcon.xcassets
      - path: Sources
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
    dependencies:
      - target: View/View
      - target: UseCase/UseCase
      - target: DataSource/DataSource
  mainTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]

schemes:
  main:
    build:
      targets:
        main: all    
    test:
      gatherCoverageData: true
      targets:
        - DataSource/DataSourceTests
        - UseCase/UseCaseTests
        - View/ViewTests
        - mainTests

