name: DataSource
targets:
  DataSource:
    scheme:
      testTargets:
        - DataSourceTests
    type: framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: DataSource
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Sources]
    info:
      path: Sources/Info.plist
  DataSourceTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    info:
      path: Tests/Info.plist

